version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=luis
      - POSTGRES_PASSWORD=12345678aA
      - POSTGRES_DB=polls
    volumes:
      - notes_pg_data:/bitnami/postgresql

volumes:
  notes_pg_data:

